export { scenarioMatrix, scenarioIds, getScenario } from './scenarioMatrix'
export type { ScenarioEntry } from './scenarioMatrix'
export { stressConfig } from './stressConfig'
export type { StressConfig } from './stressConfig'
export { SESSION_CONFIG, getWarningTriggerMs } from './sessionConfig'
export { UX_DELAYS } from './uxDelays'
